/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JToolBar;

/**
 *
 * @author Sergio Cruz
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pndEscritorio = new javax.swing.JDesktopPane();
        LabelDiseño = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnRegistrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnConsultarHistoria = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblTxtHora = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        mnBarra = new javax.swing.JMenuBar();
        MainMenuRegistrar = new javax.swing.JMenu();
        opcmRegistrar = new javax.swing.JMenuItem();
        opcmMedico = new javax.swing.JMenuItem();
        MainMenuConsultar = new javax.swing.JMenu();
        opcmConsultar = new javax.swing.JMenuItem();
        opcmConsultarHistoria = new javax.swing.JMenuItem();
        MainMenuSalir = new javax.swing.JMenu();
        opcmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pndEscritorio.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));

        LabelDiseño.setText("Diseñado por: Daniel Torres y Sergio Cruz");
        pndEscritorio.add(LabelDiseño);
        LabelDiseño.setBounds(460, 280, 240, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pndEscritorio.add(jPanel1);
        jPanel1.setBounds(0, 620, 1200, 30);

        jToolBar1.setRollover(true);

        btnRegistrar.setText("Registrar");
        btnRegistrar.setFocusable(false);
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnRegistrar);

        btnConsultar.setText("Consultar");
        btnConsultar.setFocusable(false);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnConsultar);

        btnConsultarHistoria.setText("CHistoria");
        btnConsultarHistoria.setFocusable(false);
        btnConsultarHistoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultarHistoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnConsultarHistoria);

        btnBuscar.setText("Buscar");
        btnBuscar.setFocusable(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIconTextGap(3);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBuscar);

        lblTxtHora.setText("Hora:");
        jToolBar1.add(lblTxtHora);

        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHora.setText("00:00:00");
        lblHora.setAutoscrolls(true);
        lblHora.setIconTextGap(8);
        jToolBar1.add(lblHora);

        pndEscritorio.add(jToolBar1);
        jToolBar1.setBounds(0, 570, 1200, 50);

        MainMenuRegistrar.setText("Registrar");

        opcmRegistrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcmRegistrar.setText("Registrar Paciente");
        MainMenuRegistrar.add(opcmRegistrar);

        opcmMedico.setText("Registar Medico");
        MainMenuRegistrar.add(opcmMedico);

        mnBarra.add(MainMenuRegistrar);

        MainMenuConsultar.setText("Consultar");

        opcmConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcmConsultar.setText("Consultar Paciente");
        MainMenuConsultar.add(opcmConsultar);

        opcmConsultarHistoria.setText("Consultar Historia Clinica");
        MainMenuConsultar.add(opcmConsultarHistoria);

        mnBarra.add(MainMenuConsultar);

        MainMenuSalir.setText("Salir");

        opcmSalir.setText("Salir");
        MainMenuSalir.add(opcmSalir);

        mnBarra.add(MainMenuSalir);

        setJMenuBar(mnBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pndEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pndEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLabelDiseño() {
        return LabelDiseño;
    }

    public void setLabelDiseño(JLabel LabelDiseño) {
        this.LabelDiseño = LabelDiseño;
    }

    public JMenu getMainMenuConsultar() {
        return MainMenuConsultar;
    }

    public void setMainMenuConsultar(JMenu MainMenuConsultar) {
        this.MainMenuConsultar = MainMenuConsultar;
    }

    public JMenu getMainMenuRegistrar() {
        return MainMenuRegistrar;
    }

    public void setMainMenuRegistrar(JMenu MainMenuRegistrar) {
        this.MainMenuRegistrar = MainMenuRegistrar;
    }

    public JMenu getMainMenuSalir() {
        return MainMenuSalir;
    }

    public void setMainMenuSalir(JMenu MainMenuSalir) {
        this.MainMenuSalir = MainMenuSalir;
    }

    public JMenuBar getMnBarra() {
        return mnBarra;
    }

    public void setMnBarra(JMenuBar mnBarra) {
        this.mnBarra = mnBarra;
    }

    public JMenuItem getOpcmConsultar() {
        return opcmConsultar;
    }

    public void setOpcmConsultar(JMenuItem opcmConsultar) {
        this.opcmConsultar = opcmConsultar;
    }

    public JMenuItem getOpcmRegistrar() {
        return opcmRegistrar;
    }

    public void setOpcmRegistrar(JMenuItem opcmRegistrar) {
        this.opcmRegistrar = opcmRegistrar;
    }

    public JMenuItem getOpcmSalir() {
        return opcmSalir;
    }

    public void setOpcmSalir(JMenuItem opcmSalir) {
        this.opcmSalir = opcmSalir;
    }

    public JDesktopPane getPndEscritorio() {
        return pndEscritorio;
    }

    public void setPndEscritorio(JDesktopPane pndEscritorio) {
        this.pndEscritorio = pndEscritorio;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getLblHora() {
        return lblHora;
    }

    public void setLblHora(JLabel lblHora) {
        this.lblHora = lblHora;
    }

    public JLabel getLblTxtHora() {
        return lblTxtHora;
    }

    public void setLblTxtHora(JLabel lblTxtHora) {
        this.lblTxtHora = lblTxtHora;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JButton getBtnConsultar() {
        return btnConsultar;
    }

    public void setBtnConsultar(JButton btnConsultar) {
        this.btnConsultar = btnConsultar;
    }

    public JButton getBtnConsultarHistoria() {
        return btnConsultarHistoria;
    }

    public void setBtnConsultarHistoria(JButton btnConsultarHistoria) {
        this.btnConsultarHistoria = btnConsultarHistoria;
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public void setBtnRegistrar(JButton btnRegistrar) {
        this.btnRegistrar = btnRegistrar;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JMenuItem getOpcmConsultarHistoria() {
        return opcmConsultarHistoria;
    }

    public void setOpcmConsultarHistoria(JMenuItem opcmConsultarHistoria) {
        this.opcmConsultarHistoria = opcmConsultarHistoria;
    }

    public JMenuItem getOpcmMedico() {
        return opcmMedico;
    }

    public void setOpcmMedico(JMenuItem opcmMedico) {
        this.opcmMedico = opcmMedico;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDiseño;
    private javax.swing.JMenu MainMenuConsultar;
    private javax.swing.JMenu MainMenuRegistrar;
    private javax.swing.JMenu MainMenuSalir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarHistoria;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblTxtHora;
    private javax.swing.JMenuBar mnBarra;
    private javax.swing.JMenuItem opcmConsultar;
    private javax.swing.JMenuItem opcmConsultarHistoria;
    private javax.swing.JMenuItem opcmMedico;
    private javax.swing.JMenuItem opcmRegistrar;
    private javax.swing.JMenuItem opcmSalir;
    private javax.swing.JDesktopPane pndEscritorio;
    // End of variables declaration//GEN-END:variables

}
